---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4659526218-ACdRqMGrpp67aILIBTk91DPdQF6uJvR8SIjsHUD
:access_token_secret: 7c8DccUPbUVvhgt4xdRy1GMhHDWnWgFZ7jYiVi6V0R2jy
